### ISSUE TITLE
msgpack deserialisation much slower compared to json.net in Unity?

### ISSUE THREAD

**Issue by shongololo** [msgpack/msgpack-cli#110]
I am doing some experiments with deserialisation speed of msgPack vs. Json.NET in Unity3d. I have found that msgPack is substantially slower, to the order of 100 times. On the other hand, the serialisation speed is much faster than Json.NET. 

I've described the code and question at this [stack overflow post](http://stackoverflow.com/questions/32232674/how-to-compare-performance-of-messagepack-cli-and-json-net-deserializers).

Is there something I am doing wrong? Or a manner in which to speed up the deserialisation?

Thanks.

**Comment by yfakariya** [comment]
Thank you for reporting! I don't have deep knowledge for JSON.NET in Unity3D and this slow operation should be investigated, but there is an optimization for it. Could you use pre-generated serializer (created via mpu.exe or `SerializerGenerator` class) instead of runtime generated serializer? The runtime serializer uses reflection to avoid code generation and unexpected JIT.

**Comment by shongololo** [comment]
Thanks for the suggestion. Are there some examples for how to use the SerializerGenerator class?

**Comment by yfakariya** [comment]
https://github.com/msgpack/msgpack-cli/wiki/Xamarin-and-Unity#generate-serializers may help you.
