### ISSUE TITLE
Issue when packing Abstract classes in an object graph

### ISSUE THREAD

**Issue by donalfenwick** [msgpack/msgpack-cli#122]
There seems to be an issue when calling pack on abstract classes inside an object graph.

If I assign a concrete type to a variable of abstract type and pass that to the pack function (using dynamic type) it works.
However if I add it as a property of another object and pass the root object to the pack function it fails telling me that the class cannot be instantiated instead of trying to instantiate the concrete type.

See the example below..

```cs
using MsgPack.Serialization;
using System.Collections.Generic;
using System.IO;

namespace TestMsgPackApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // passing the abstract class as the root object works OK
            using (MemoryStream stream = new MemoryStream())
            {
                Person responseObject = new Student() { Name = "John", Subjects = new List<string>() };
                var serializer = MessagePackSerializer.Get<dynamic>();
                serializer.Pack(stream, responseObject);
                stream.Position = 0;
                var unpackedObject = serializer.Unpack(stream);
            }

            // passing the abstract class as part of an object tree fails to pack
            using (MemoryStream stream = new MemoryStream())
            {
                ResponseObject responseObject = new ResponseObject() {
                    Person = new Student() { Name = "John", Subjects = new List<string>() }
                };
                var serializer = MessagePackSerializer.Get<dynamic>();
                serializer.Pack(stream, responseObject);
                stream.Position = 0;
                var unpackedObject = serializer.Unpack(stream);
            }
        }
    }


    public abstract class Person
    {
        public string Name { get; set; }
    }

    public class Student : Person
    {
        public List<string> Subjects { get; set; }
    }

    public class ResponseObject
    {
        public Person Person { get; set; }
    }

}
```

**Comment by yfakariya** [comment]
Thank you for reporting. It is by design, but I also notice that I forgot to mention it.
`MessagePackSerializer.Get<dynamic>()` should be compiled as `MessagePackSerializer.Get<object>()` and it means that "root" object should be dynamic (that is the type information will be embeded in the stream. Therefore, the actual type of `Person` property will not be serialized. You can serialize `ResponseObject` with `[MessagePackRuntimeType]` attribute as following:
```c#
public class ResponseObject
{
        [MessagePackRuntimeType]
        public Person Person { get; set; }
}
```
I'll add wiki to explain this.

**Comment by donalfenwick** [comment]
Thanks, but couldn't the behavior caused by the MessagePackRuntimeType attribute simply be applied to any property with an abstract type to avoid needing to decorate the all classes with this attribute?

**Comment by yfakariya** [comment]
Yes, currently polymorphism is opt-in feature because it hurts interoperability for other languages and interoperability is key factor of msgpack over native serializers including `BinaryFormatter` and `NetDataContractSerializer`. For my reference, could you tell me how many abstract typed members do you have?

**Comment by donalfenwick** [comment]
OK no worries. Not so many abstract types in the API app currently, but the data contracts exist in a different package to the application code so I would need to add MsgPack to it as a dependency as well as the api to enable pollymorphisim via the attributes.
