### ISSUE TITLE
Option to skip null members when serializing (autogenerated)?

### ISSUE THREAD

**Issue by Tinche** [msgpack/msgpack-cli#136]
Hi!

I'm using generation of serializers. I have a class (that I want to serialize) with a string member, with a MessagePackMember attribute on it. When I serialize an instance, the generated msgpack contains a key-value pair (member: nil), which is correct.

However, it would be great if there was an option to skip serializing members with null values. Currently I'm editing the generated code to put in an if check manually, but adding a property (skipSerializingWhenNull?) to MessagePackMember would be super!

**Comment by yfakariya** [comment]
Hi!
Thank you for your suggestion, it sounds good, but I have a question. Because `null` only occupies one byte in msgpack, placing `null` should not be a matter as long as you use `SerializationMethod.Array`. So, do you say that you want to omit property names themselves when you use `SerializationMrthod.Map`?

**Comment by Tinche** [comment]
Yes, I'm using SerializationMethod.Map, so that's what I meant, sorry for not specifying. Correct, to ignore the key:value pair entirely (omit the property name too) when the value is null.

**Comment by yfakariya** [comment]
Change milestone to the future, because it is harder than I thought. It requires checking all values of the object because msgpack format needs map entry count in advance.

**Comment by yfakariya** [comment]
This issue should be solved in 0.8.
Feel free to reopen if you find any issues.
