### ISSUE TITLE
Question: Serializing "Exception", gives NotSupportedException

### ISSUE THREAD

**Issue by LordMike** [msgpack/msgpack-cli#166]
Hi,

I'm trying to serialize an `Exception` with `ObjectPacker`, and I get an error: 

    An unhandled exception of type 'System.NotSupportedException' occurred in MsgPack.dll
    
    Additional information: Specified method is not supported.`

But types that inherit from Exception (custom or part of .NET such as `FileNotFoundException`) serialize just fine. Is there something special about Exception?

**Comment by yfakariya** [comment]
No, there are no special handling for exception now, and serializing exception is not supported.

Alghouth if the type has a public parameterless constructor and at least one read-write properties/fields can be handled with serializers, it does not really work because some important members cannot be deserialized such as `Message` and more important `StackTrace`. In this point, restoring `StackTrace` is extremely hard because there are no ways to restore it except internal methods to support .NET remoting.

BTW, I have a question. When I reproduce this issue, I had seen that `Exception` had also been (incompletely) serializable and then I noticed that you said 'ObjectPacker` which is not part of MessagePack for CLI. As I know, it is the type existed in "MessagePack C#". Do you use MessagePack for C#? If so, please contact original author of it.

**Comment by LordMike** [comment]
Ooooh... Damn. Almost the same name.

I figured it'd be a hard one to crack as Exception is so closed down. So I ended up creating a "proxy" which basically contains all the interesting stuff. I then serialize this and throw an exception clientside with this proxy embedded.

I've switched to MsgPack.Cli now.
