### ISSUE TITLE
feature request : Allow inheritance to be packed

### ISSUE THREAD

**Issue by sueds** [msgpack/msgpack-cli#58]
If you have a collection of an object unfortunately messagepack save the base class and not the actual class derive from the base class.

for instance if I have a list of BaseClass and I had an object DerivedFromBase message pack only save the DerivedFrombase as a BaseClass. Which is unfortunate for saving class. I manage to implement an hack using ipacker and such but I realised most of my list derive from a base class and I had to to it  over an over. 

So I think it could be a great feature to had to message pack

**Comment by yfakariya** [comment]
Thank you for feedback. It should be accomplished with when request #47 is implented because it enables you to embed actual type information to the serialized stream.

Side note: Currently, msgpack for cli does NOT embed type information because it is not interoperable at all (for example, assembly-qualified-name is not useless for Java or Ruby).

**Comment by yfakariya** [comment]
I've written the spec draft. Would you review it? https://gist.github.com/yfakariya/fb6d5c66fa4d8a82346b

**Comment by sueds** [comment]
Yeah definitely. I'll let you know on this page. Really nice feature and quite important for most of my project.

**Comment by SimonCropp** [comment]
any update on this?

**Comment by yfakariya** [comment]
I'm testing it and going to clean up it for future maintenance now.

**Comment by yfakariya** [comment]
Hi, all. 0.6.0-beta2 has implementation of this. Please try it!

**Comment by yfakariya** [comment]
Fixed in 0.6.0.
