### ISSUE TITLE
C# and C++ pack_map and pack_array compatibility

### ISSUE THREAD

**Issue by camilleri** [msgpack/msgpack-cli#71]
Hi,

I'm trying to encode a msgpack map of msgpack objects, these msgpack objects can be any primitive type and also a packed array. I have a C++ server which is consumed by C++ and C# applications, they all communicate with serialized mgpack maps of msgpack objects.

For communicating with the server in C++ I'm using pack_map and pack_array for packing the map and the array which works nicely.

In C# I'm using a MessagePackObjectDictionary for packing the map which works, but I'm not able to pack the array to a msgpack object so that it can be successfully decoded by the C++ server.

I've tried to add the array by using the constructors of http://cli.msgpack.org/doc/html/AllMembers_T_MsgPack_MessagePackObject.htm as:

1)  Array as a "List<MessagePackObject>"
    List<MessagePackObject> my_list = new List<MessagePackObject>(1);
    my_list .Add("item1");

    msgPackDict.Add("list", new MessagePackObject(my_list));

2) Array as a flat MessagePackObject[]
    msgPackDict.Add("list", new MessagePackObject[1] { "item1" });

Where msgPackDict is a MessagePackObjectDictionary declared as 
MessagePackObjectDictionary msgPackDict = new MessagePackObjectDictionary(1);

Can someone help or provide some advice? Please note that the MessagePackObjectDictionary of primitive types works nicely between the C# consumer and the C++ server, the problem comes when using arrays.

Thanks!

**Comment by yfakariya** [comment]
Sorry for too late response.

It is by design. For compatibility reason (C# spec does not guarantee order of members in the metadata), msgpack for cli sorts members as alphabetical order before serialize. You can avoid this specifying [MessagePackMember] attributes with numeric id.

I will add configuration flag to avoid this behavior in the future.

**Comment by yfakariya** [comment]
Sorry, I cancel the last line of previous post because I really saw that C# 3.0 compiler does not emit members in order as declared in source code. If msgpack for cli did not determine the order of serialized members which use the array-based serialization, it would lead very strange behavior. In the end, only solution is qualify members by [MessagePackMember] custom attribute with explicit IDs.
