### ISSUE TITLE
Create MessagePackSerializer<T> for internal type

### ISSUE THREAD

**Issue by drewnoakes** [msgpack/msgpack-cli#76]
I'm not sure if this is possible, but I would like to create `MessagePackSerializer<T>` instances for where `T` is an `internal` type.

I'm building a library which uses messages internally and I don't want to make these publicly visible to users of the library.

**Comment by yfakariya** [comment]
It is possible at the sacrifice of performance -- code generation based serializer cannot access their `internal` type because generated code besides on own assembly, not a target type's assembly. I think there are two options to accompilsh it:
* Allows CodeDOM based generator generate it, and you import it your project.
* Allows select (internal) reflection based serializers when you pass `internal` type.
I'm tuckling another big enhancement now, so I want postpone this enhancement.

And you already have an option -- implementing a custom serializer which derived from `MessagePackSerializer<T>` and register it via `SerializationContext.Serializers.Register()`.

**Comment by yfakariya** [comment]
I will not add `internal` type support currently. Please reopen and give more reason to implement it. Thanks.
