### ISSUE TITLE
StackOverflow when trying to pack an object with circulal reference

### ISSUE THREAD

**Issue by aboudoux** [msgpack/msgpack-cli#83]
Hi,
An exception occurs if I want to serialize something like that :

 [Serializable]
    public class Parent
    {
        public Parent()
        {
            Children = new List<Child>();
        }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public List<Child> Children { get; set; }
    }

    [Serializable]
    public class Child
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public Parent Parent { get; set; }
    }

var source = new Parent() { FirstName = "ALPHA", LastName = "Bravo" };
source.Children.Add(new Child() { FirstName = "ALPHA", LastName = "Charlie", Parent = source });

the exception is a System.StackOverflowException. I guess the packer enter in an infinite loop when it encounter the Parent property member.

**Comment by aboudoux** [comment]
Sorry, I've got my answer in your documentation : Cyclic References.
I'm disappointed because I can't find a fast and simple serializer which handle this issue

**Comment by yfakariya** [comment]
Oh... it is not easy to solve because msgpack *protocol* does not define reference, so cyclic reference cannot be solved as long as the library keeps interoperability.

In addition, I think it is hard to keep high performance when we implement cyclic referenced object graph deserialization, and the work should be hard in many languages, so it might not be solved soon.

**Comment by akkumaru** [comment]
Is there any way to **exclude** any property that has circular reference?

I have tried MessagePackMemberAttribute and DataMemberAttribute, but the problematic property always gets hit and consequently raises StackOverflowException. Also, NonSerializedAttribute cannot be applied to properties; only fields.

**Comment by yfakariya** [comment]
`MessagePackIgnoreAttribute` should help you.

**Comment by akkumaru** [comment]
Hi, thanks for the reply. But it still gets hit.

Here is the code for the problematic attribute; the return JSonConvert line always raises a StackOverflowException.

`public RuleObj RuleObj
        {
            get
            {
                if (this.SerializedRule == null) { return null; }
                return JsonConvert.DeserializeObject<RuleObj>(this.SerializedRule);
            }

            set { this.SerializedRule = JsonConvert.SerializeObj(value); }
        }`

**Comment by yfakariya** [comment]
Thank you for reporting. It looks bug, but I cannot reproduce stackover flow. Could you show me more concrete repro code? For your reference, I used following test code:
```csharp
[Test]
public void TestMessagePackIgnoreCanAvoidStackOverflow()
{
    var serializer = new SerializationContext().GetSerializer<Issue83Continuous>();
    using (var buffer = new MemoryStream())
    {
        serializer.Pack(buffer, new Issue83Continuous {RuleObj = new RuleObj {Str = "a", Int = 3}});
        buffer.Position = 0;
        var result = serializer.Unpack(buffer);
        Assert.That(result.RuleObj, Is.Not.Null);
        Assert.That(result.RuleObj.Str, Is.EqualTo("a"));
        Assert.That(result.RuleObj.Int, Is.EqualTo(3));
        Assert.That(result.SerializedRule, Is.EqualTo("{\"Str\":\"a\",\"Int\":3}"));
    }
}

public class Issue83Continuous
{
    public string SerializedRule {get; set;}

    [MessagePackIgnoreAttribute]
    public RuleObj RuleObj
    {
        get
        {
            if (this.SerializedRule == null) {return null;}
            return JsonConvert.DeserializeObject<RuleObj>(this.SerializedRule);
        }

        set {this.SerializedRule = JsonConvert.SerializeObject(value);}
    }
}

public class RuleObj
{
    public string Str {get; set;}
    public int Int {get; set;}
}
```

**Comment by akkumaru** [comment]
Hi, here is a more complete class, notice that RuleObj is an inner class member.

`public class ActivityRule : DbEntity
    {
        public string SerializedRule { get; set; }
        
        [MessagePackIgnore]
        public RuleObj RuleObj
        {
            get
            {
                if (this.SerializedRule == null) { return null; }
                return JsonConvert.DeserializeObject<RuleObj>(this.SerializedRule);
            }

            set { this.SerializedRule = JsonConvert.SerializeObject(value); }
        }
    }`

**Comment by yfakariya** [comment]
Thank you, I forgot most important "recursive member".

**Comment by yfakariya** [comment]
@akkumaru Umm.... I failed to reproduce with your code in both of 0.6 and 0.7 branches. Could you tell me what code do you reproduce? My updated test code is here (its assertions are naive, but this code can check StackOverflowException):
```csharp
var serializer = new SerializationContext().GetSerializer<ActivityRule>();
using (var buffer = new MemoryStream())
{
	serializer.Pack(buffer, 
		new ActivityRule {
			RuleObj = new RuleObj { 
				Key = "k", 
				Value = "v", 
				Operator = OperatorType.EQUALS, 
				SubRules = new List<RuleObj> { 
					new RuleObj {Key = "k0", Value = "v0"} 
				}
			}
		} 
	);
	buffer.Position = 0;
	var result = serializer.Unpack(buffer);
	Assert.That(result.RuleObj, Is.Not.Null);
	Assert.That(result.RuleObj.Key, Is.EqualTo("k"));
	Assert.That(result.RuleObj.Value, Is.EqualTo("v"));
	Assert.That(result.RuleObj.Operator, Is.EqualTo(OperatorType.EQUALS));
	Assert.That(result.RuleObj.SubRules, Is.Not.Null);
	Assert.That(result.RuleObj.SubRules.Count, Is.EqualTo(1));
}
```

**Comment by akkumaru** [comment]
@yfakariya Yes, I wrote a couple of tests as well and they would succeed as long as I do not use Entity Framework's automatic loading feature.

To elaborate, these classes are actually part of a solution utilizing C# Entity Framework. ActivityRule has a reference to another parent class, and both represent a DB entity; RuleObj does not, it only serves as a helper class to the UI. I am trying to pack these DB entities so that I would be able to transfer them to another environment, thus I'm only interested in serializing classes that actually hold data.

Here is what I found so far. If I try to fetch both the parent class and ActivityRule, then serialize them the stackoverflow exception will kick in. Such steps will not work:

var fullParents = context.Parents.Where(some condition).Include(p => p.ActivityRule);
serializer.Pack(stream, fullParents);

But if I try to fetch the parent first, then embed the ActivityRule through subsequent expensive DB calls it runs fine:

var parentList = context.Parents.Where(some condition).ToList();
foreach (var p in parentList)
{
   p.ActivityRule = context.ActivityRules.FirstOrDefault(a => a.ParentId == p.id);
}
serializer.Pack(stream, parentList);

All this without even putting [MessagePackIgnore] to the class members.

**Comment by yfakariya** [comment]
Hmm... BTW, I tried to create very intentional cyclic reference like below:
```csharp
var rule = new RuleObj { Key = "k", Value = "v", Operator = OperatorType.EQUALS, SubRules = new List<RuleObj>() };
rule.SubRules.Add(rule); // make cyclic referfence
var obj = new ActivityRule { RuleObj = rule };
```
I faced `JsonSerializationException` because JSON.NET detect circular reference. So, I wonder why you did not face `JsonSerializationException`.

**Comment by akkumaru** [comment]
Well, I think, data-wise, we never had any actual circular reference. We use RuleObj to construct some kind of tree structure, so the root will never be a child of any leaf, and that avoids us from JSonSerializationException.

**Comment by yfakariya** [comment]
I see. Could you post callstack when you are facing StackOverflowException?

**Comment by akkumaru** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5345728/16340752/b8de4274-3a21-11e6-8f2a-d72da47e663f.png)

I'm not sure really, since the error message in event viewer does not contain the stack trace. All it says just that it has hit a StackOverflowException. When I debug in VS, sometimes a debug window will point to RuleObj (as the class member of ActivityRule) as the exception source.

But when opening the dump file, the stack frame drop down menu indicates that there were massive multiple calls to these three routines. It is so many that the maximum number of stack frames supported by VS is exceeded.

**Comment by yfakariya** [comment]
Thank you, but it still hard to investigate.
